### ISSUE TITLE
Add a "Join the Beta Waitlist" button

### ISSUE THREAD

**Issue by jeffrey-tc** [actually-colab/www#11]
![www](https://user-images.githubusercontent.com/5074313/115973764-2480fd80-a51d-11eb-9b22-392de4140660.png)

**Comment by baileytincher** [comment]
- [ ] Form allows users to specify their email, job title, and an optional "how will you use colab"
- [ ] Create a lambda that writes to a dynamo table
- [ ] Send an email confirmation that they're on the list?
- [ ] Show the size of the waitlist? (once it gets big...)
